In [2]:
import os
os.environ["TQDM_DISABLE"] = "1"  # 完全禁用进度条
import akshare as ak

In [ ]:
df_stock = ak.stock_zh_a_spot_em()

In [14]:
# 期货实时行情（指定合约）
df_futures = ak.futures_zh_spot(symbol="AU2608", market="CF")
df_futures

,symbol,time,open,high,low,current_price,bid_price,ask_price,buy_vol,sell_vol,hold,volume,avg_price,last_close,last_settle_price
0,黄金2608,023000,884.94,891.64,883.0,891.14,890.84,891.14,7,16,83392.0,79893,0.0,0.0,879.22

In [15]:
df_futures = ak.futures_zh_spot(symbol="IC2612", market="FF")
df_futures

,symbol,time,open,high,low,current_price,hold,volume,amount
0,中证500指数期货2612,15:00:00,7161.4,7518.0,7032.8,7517.2,76338.0,36710,268218886.6

In [19]:
option_finance_board_df = ak.option_finance_board(symbol="南方中证500ETF期权", end_month="202608")
option_finance_board_df

               日期             合约交易代码     当前价    涨跌幅     前结价     行权价  数量
0   2026072294258  510500C2608A08000  0.2642  -5.58  0.2798   7.859  50
1   2026072294258  510500C2608A08250  0.1696  -6.30  0.1810   8.104  50
2   2026072294258  510500C2608A08500  0.1065  -7.47  0.1151   8.350  50
3   2026072294258  510500C2608A08750  0.0664  -9.29  0.0732   8.595  50
4   2026072294258  510500C2608A09000  0.0416 -12.24  0.0474   8.841  50
5   2026072294258  510500C2608A09250  0.0266 -11.33  0.0300   9.086  50
6   2026072294258  510500C2608A09500  0.0180  -9.09  0.0198   9.332  50
7   2026072294258  510500C2608A09750  0.0117 -10.69  0.0131   9.578  50
8   2026072294258  510500C2608A10000  0.0081 -12.90  0.0093   9.823  50
9   2026072294258  510500P2608A08000  0.3631  -0.06  0.3633   7.859  50
10  2026072294258  510500P2608A08250  0.5112   1.27  0.5048   8.104  50
11  2026072294258  510500P2608A08500  0.7014   1.24  0.6928   8.350  50
12  2026072294258  510500P2608A08750  0.9016   0.73  0.8951   8.595  50
13  2026072294258  510500P2608A09000  1.1166  -0.30  1.1200   8.841  50
14  2026072294258  510500P2608A09250  1.3467  -0.59  1.3547   9.086  50
15  2026072294258  510500P2608A09500  1.6279   2.80  1.5836   9.332  50
16  2026072294258  510500P2608A09750  1.8000  -1.51  1.8276   9.578  50
17  2026072294258  510500P2608A10000  2.1216   2.75  2.0648   9.823  50
18  2026072294258  510500C2608A07750  0.3879  -3.36  0.4014   7.613  50
19  2026072294258  510500P2608A07750  0.2401  -2.83  0.2471   7.613  50
20  2026072294258  510500C2608A10500  0.0044  -8.33  0.0048  10.314  50
21  2026072294258  510500P2608A10500  2.5323  -0.99  2.5575  10.314  50
22  2026072294258  510500C2608A07500  0.5541  -1.21  0.5609   7.367  50
23  2026072294258  510500P2608A07500  0.1546  -3.80  0.1607   7.367  50
24  2026072294258  510500C2608A07250  0.7499  -0.13  0.7509   7.122  50
25  2026072294258  510500P2608A07250  0.0937  -8.05  0.1019   7.122  50
26  2026072294258  510500C2608M07250  0.6334  -2.04  0.6466   7.250  50
27  2026072294258  510500C2608M07500  0.4562  -3.45  0.4725   7.500  50
28  2026072294258  510500C2608M07750  0.3148  -4.61  0.3300   7.750  50
29  2026072294258  510500C2608M08000  0.2060  -5.50  0.2180   8.000  50
30  2026072294258  510500C2608M08250  0.1293  -8.04  0.1406   8.250  50
31  2026072294258  510500C2608M08500  0.0800 -10.11  0.0890   8.500  50
32  2026072294258  510500C2608M08750  0.0493 -11.17  0.0555   8.750  50
33  2026072294258  510500C2608M09000  0.0302 -12.97  0.0347   9.000  50
34  2026072294258  510500C2608M09250  0.0205  -9.29  0.0226   9.250  50
35  2026072294258  510500P2608M07250  0.1236  -4.85  0.1299   7.250  50
36  2026072294258  510500P2608M07500  0.1980  -2.46  0.2030   7.500  50
37  2026072294258  510500P2608M07750  0.3042   0.30  0.3033   7.750  50
38  2026072294258  510500P2608M08000  0.4456   0.34  0.4441   8.000  50
39  2026072294258  510500P2608M08250  0.6249   1.12  0.6180   8.250  50
40  2026072294258  510500P2608M08500  0.8061  -0.86  0.8131   8.500  50
41  2026072294258  510500P2608M08750  1.0369   0.64  1.0303   8.750  50
42  2026072294258  510500P2608M09000  1.2657   0.53  1.2590   9.000  50
43  2026072294258  510500P2608M09250  1.4444  -4.38  1.5106   9.250  50
44  2026072294258  510500C2608M07000  0.8477   0.92  0.8400   7.000  50
45  2026072294258  510500P2608M07000  0.0728  -8.54  0.0796   7.000  50
46  2026072294258  510500C2608M06500  1.2800  -1.12  1.2945   6.500  50
47  2026072294258  510500C2608M06750  1.0730   1.05  1.0619   6.750  50
48  2026072294258  510500P2608M06500  0.0242 -15.97  0.0288   6.500  50
49  2026072294258  510500P2608M06750  0.0431 -11.32  0.0486   6.750  50