In [2]:
import os
os.environ["TQDM_DISABLE"] = "1"  # 完全禁用进度条
import akshare as ak

In [ ]:
df_stock = ak.stock_zh_a_spot_em()

In [14]:
# 期货实时行情（指定合约）
df_futures = ak.futures_zh_spot(symbol="AU2608", market="CF")
df_futures

,symbol,time,open,high,low,current_price,bid_price,ask_price,buy_vol,sell_vol,hold,volume,avg_price,last_close,last_settle_price
0,黄金2608,023000,884.94,891.64,883.0,891.14,890.84,891.14,7,16,83392.0,79893,0.0,0.0,879.22

In [15]:
df_futures = ak.futures_zh_spot(symbol="IC2612", market="FF")
df_futures

,symbol,time,open,high,low,current_price,hold,volume,amount
0,中证500指数期货2612,15:00:00,7161.4,7518.0,7032.8,7517.2,76338.0,36710,268218886.6

In [ ]:
# 金融期权
option_finance_board_df = ak.option_finance_board(symbol="南方中证500ETF期权", end_month="202608")
option_finance_board_df.tail()

               日期             合约交易代码  当前价  涨跌幅     前结价   行权价  数量
45  2026072391533  510500P2608M07000  0.0  0.0  0.0801  7.00  50
46  2026072391533  510500C2608M06500  0.0  0.0  1.2400  6.50  50
47  2026072391533  510500C2608M06750  0.0  0.0  0.9946  6.75  50
48  2026072391533  510500P2608M06500  0.0  0.0  0.0285  6.50  50
49  2026072391533  510500P2608M06750  0.0  0.0  0.0482  6.75  50

In [11]:
option_finance_board_df = ak.option_finance_board(symbol="华泰柏瑞沪深300ETF期权", end_month="202608")
option_finance_board_df.tail()

               日期             合约交易代码     当前价    涨跌幅     前结价  行权价  数量
21  2026072394344  510300P2608M04400  0.0164 -19.61  0.0204  4.4  26
22  2026072394344  510300C2608M04300  0.4638  -0.26  0.4650  4.3  26
23  2026072394344  510300P2608M04300  0.0095 -22.13  0.0122  4.3  26
24  2026072394344  510300C2608M04200  0.5726   1.35  0.5650  4.2  26
25  2026072394344  510300P2608M04200  0.0064 -17.95  0.0078  4.2  26

In [15]:
option_finance_board_df = ak.option_finance_board(symbol="嘉实沪深300ETF期权", end_month="202608")
option_finance_board_df.tail()

,合约编码,合约简称,标的名称,类型,行权价,合约单位,期权行权日,行权交收日
117,90007820,沪深300ETF沽8月4400,沪深300ETF嘉实,认沽,4.400,10000,2026-08-26,2026-08-27
118,90007827,中证500ETF购8月2800,中证500ETF嘉实,认购,2.800,10000,2026-08-26,2026-08-27
119,90007828,中证500ETF购8月2850,中证500ETF嘉实,认购,2.850,10000,2026-08-26,2026-08-27
120,90007829,中证500ETF沽8月2800,中证500ETF嘉实,认沽,2.800,10000,2026-08-26,2026-08-27
121,90007830,中证500ETF沽8月2850,中证500ETF嘉实,认沽,2.850,10000,2026-08-26,2026-08-27

In [16]:
option_finance_board_df = ak.option_finance_board(symbol="沪深300股指期权", end_month="202608")
option_finance_board_df.tail()

,instrument,position,volume,lastprice,updown,bprice,bamount,sprice,samount
47,IO2608-P-5200,113,1,500.0,-27.0,515.2,6,519.2,6
48,IO2608-P-5300,97,0,615.4,-9.0,612.8,6,617.0,6
49,IO2608-P-5400,109,0,734.0,10.4,711.0,6,715.8,6
50,IO2608-P-5500,126,0,829.2,5.2,810.2,12,815.0,6
51,IO2608-P-5600,48,0,906.2,-17.4,909.6,6,915.0,12

In [14]:
option_contract_info_ctp_df = ak.option_contract_info_ctp()
option_contract_info_ctp_df.to_excel("option_contract_info_ctp.xlsx", index=False)

In [ ]:
# df_option = ak.option_current_em() # 全量数据，太大

  0%|          | 0/256 [00:00<?, ?it/s]

,序号,代码,名称,最新价,涨跌额,涨跌幅,成交量,成交额,持仓量,行权价,剩余日,日增,昨结,今开,市场标识
0,1,au2610C1288,沪金26年10月购1288,1.42,1.40,7000.00,15.0,19540.0,64.0,NaN,0,12.0,0.02,1.06,151
1,2,au2610C1272,沪金26年10月购1272,1.42,1.40,7000.00,3.0,4140.0,25.0,NaN,0,-2.0,0.02,1.22,151
2,3,au2610C1280,沪金26年10月购1280,1.42,1.40,7000.00,1.0,1420.0,24.0,NaN,0,0.0,0.02,1.42,151
3,4,au2610C1296,沪金26年10月购1296,1.36,1.34,6700.00,1.0,1360.0,60.0,NaN,0,0.0,0.02,1.36,151
4,5,au2610C1304,沪金26年10月购1304,1.32,1.30,6500.00,14.0,17980.0,46.0,NaN,0,7.0,0.02,1.08,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26415,26416,MO2608-C-8200,中证1000购26年08月8200,14.40,-23.80,-62.30,6829.0,14429160.0,6534.0,8200.0,30,748.0,38.20,33.60,221
26416,26417,MO2608-C-8300,中证1000购26年08月8300,10.60,-17.60,-62.41,4769.0,7690940.0,4834.0,8300.0,30,575.0,28.20,23.00,221
26417,26418,MO2608-C-8400,中证1000购26年08月8400,8.00,-13.40,-62.62,5741.0,6902520.0,5756.0,8400.0,30,38.0,21.40,16.00,221
26418,26419,HO2609-P-2500,上证50沽26年09月2500,2.20,-3.80,-63.33,577.0,179640.0,1685.0,2500.0,58,-214.0,6.00,6.00,221
26419,26420,HO2610-P-2500,上证50沽26年10月2500,3.80,-6.80,-64.15,20.0,11120.0,26.0,2500.0,86,13.0,10.60,7.80,221

:

In [19]:
news_economic_baidu_df = ak.news_economic_baidu(date="20260723")
news_economic_baidu_df

,日期,时间,地区,事件,公布,预期,前值,重要性
0,2026-07-23,00:00,俄罗斯,俄罗斯6月PPI年率(%),10.50,NaN,9.40,1
1,2026-07-23,00:00,俄罗斯,俄罗斯6月PPI月率(%),-0.10,NaN,2.50,1
2,2026-07-23,00:00,俄罗斯,俄罗斯6月工业产值年率(%),0.60,0.1,-0.70,1
3,2026-07-23,01:00,美国,美国7月22日20年期国债竞拍-投标倍数(倍),2.64,NaN,2.75,1
4,2026-07-23,01:00,美国,美国7月22日20年期国债竞拍-高配置百分比(%),15.13,NaN,56.57,1
...,...,...,...,...,...,...,...,...
101,2026-07-23,23:30,美国,美国7月23日4星期国债竞拍-中标利率(%),NaN,NaN,3.66,1
102,2026-07-23,23:30,美国,美国7月23日4星期国债竞拍-投标倍数(倍),NaN,NaN,2.57,1
103,2026-07-23,23:30,美国,美国7月23日8周国债竞拍-中标利率(%),NaN,NaN,3.65,1
104,2026-07-23,23:30,美国,美国7月23日4星期国债竞拍-总金额(亿美元),NaN,NaN,1164.47,1
105,2026-07-23,23:30,美国,美国7月23日8周国债竞拍-投标倍数(倍),NaN,NaN,2.84,1